### ISSUE TITLE
Fails on Python 3.6/ Ubuntu

### ISSUE THREAD

**Issue by talaikis** [romanvm/WsgiBoostServer#1]
```text
 /usr/bin/ld: cannot find -lboost_python-py36
 /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/lib
st_coroutine.a(standard_stack_allocator_posix.o): relocation R_X86_64_32 agai
 `.bss' can not be used when making a shared object; recompile with -fPIC
 /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_corouti
a: error adding symbols: Bad value
 collect2: error: ld returned 1 exit status
 error: command 'g++' failed with exit status 1

 ----------------------------------------
mand "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/
/pip-3ufrjpd8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);cod
.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
nstall --record /tmp/pip-m85gw_yz-record/install-record.txt --single-version-
ernally-managed --compile" failed with error code 1 in /tmp/pip-3ufrjpd8-buil

```

**Comment by romanvm** [comment]
First, please provide proper diagnostic info. The error message above is truncated from all sides and not readable. And which Ubuntu are you talking about?

The general problem with Python 3.6 is that Boost libraries from the official Ubuntu ppa do not include pre-complied Boost.Python for 3.6. The build script `setup.py` was tested on Ubuntu 16.04 LTS (PC) and Debian Jessie (Raspbian) with Python 2/3 and Boost libs from the official ppas. If you want to use custom versions of Boost and/or Python, you need to build the necessary Boost libs for yourself. I'll add the info about custom builds on Linux to the Readme. For now you can either use Python and Boost from the official ppas or look into `.travis.yml` to see how a custom build is done.

**Comment by talaikis** [comment]
OK, sorry for lack of details, I had managed to build it under Ubuntu 16.04/ Anaconda Python 3.6:

```test
sudo ./bootstrap.sh --with-python=/home/ubuntu/anaconda3/bin/python -with-python-version=3.6 --with-python-root=/home/ubuntu/anaconda3/lib
sudo ./b2 link=static runtime-link=static variant=release --with-regex --with-system --with-coroutine --with-context --with-filesystem --with-iostreams --with-date_time --with-python

export BOOST_ROOT=/home/ubuntu/boost_1_63_0
export BOOST_LIBRARYDIR=/home/ubuntu/boost_1_63_0/stage/lib
```

Didn't tested yet though :)

**Comment by romanvm** [comment]
I've noticed a bug (a missing library dependency) in `setup.py` script that might cause WsgiBoostServer fail to load if it it's built against custom Python and Boost versions. Wait until I update the build script on `master` branch.

**Comment by romanvm** [comment]
I have updated `setup.py` build script and build instructions in the Readme. Try to compile now if you are having issues.

**Comment by romanvm** [comment]
Is there any follow-up? Have you been able to compile the recent versions?

**Comment by talaikis** [comment]
Under Python 3.5, yes, no problem. Not under Python 3.6 - "python setup.py build" stops with "/usr/bin/ld: cannot find -lboost_python-py36"

**Comment by romanvm** [comment]
Yes, `libboost-all-dev` from Ubuntu ppa is shipped with Boost.Python pre-built against Python 2.7 and 3.5. You need to compile the necessary version from sources.

From time to time I'm thinking of re-writing the server into a self-contained package using headers-only Pybind11 and Asio libraries, but for that I would have to drop serving static files (that depends on Boost.Filesystem and Boost.Streams), so I have doubts.

**Comment by romanvm** [comment]
I pushed v.2.0 to master in which Python bindings were converted from `Boost.Python` to `Pybind11`, so you no longer need to link against a version-specific Boost.Python library. Only generic Boost libraries are needed.
